// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhuqdjjppnmtqsmtozny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5odXFkampwcG5tdHFzbXRvem55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTg3ODIsImV4cCI6MjA3MDg5NDc4Mn0._NU4Q0o6RqMUpyegiGCGg8op6GT70nDiYIc97o95KL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});